// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module top_tx_adding_pilot (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        temp1_re397_dout,
        temp1_re397_empty_n,
        temp1_re397_read,
        temp1_im398_dout,
        temp1_im398_empty_n,
        temp1_im398_read,
        temp2_re399_din,
        temp2_re399_full_n,
        temp2_re399_write,
        temp2_im400_din,
        temp2_im400_full_n,
        temp2_im400_write
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] temp1_re397_dout;
input   temp1_re397_empty_n;
output   temp1_re397_read;
input  [15:0] temp1_im398_dout;
input   temp1_im398_empty_n;
output   temp1_im398_read;
output  [15:0] temp2_re399_din;
input   temp2_re399_full_n;
output   temp2_re399_write;
output  [15:0] temp2_im400_din;
input   temp2_im400_full_n;
output   temp2_im400_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg temp1_re397_read;
reg temp1_im398_read;
reg temp2_re399_write;
reg temp2_im400_write;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [9:0] data_symb1_M_real_V_address0;
reg    data_symb1_M_real_V_ce0;
reg    data_symb1_M_real_V_we0;
wire   [15:0] data_symb1_M_real_V_q0;
reg    data_symb1_M_real_V_ce1;
reg    data_symb1_M_real_V_we1;
reg   [9:0] data_symb1_M_imag_V_address0;
reg    data_symb1_M_imag_V_ce0;
reg    data_symb1_M_imag_V_we0;
wire   [15:0] data_symb1_M_imag_V_q0;
reg    data_symb1_M_imag_V_ce1;
reg    data_symb1_M_imag_V_we1;
reg   [9:0] data_symb2_M_real_V_address0;
reg    data_symb2_M_real_V_ce0;
reg    data_symb2_M_real_V_we0;
wire   [15:0] data_symb2_M_real_V_q0;
reg    data_symb2_M_real_V_ce1;
reg    data_symb2_M_real_V_we1;
reg   [9:0] data_symb2_M_imag_V_address0;
reg    data_symb2_M_imag_V_ce0;
reg    data_symb2_M_imag_V_we0;
wire   [15:0] data_symb2_M_imag_V_q0;
reg    data_symb2_M_imag_V_ce1;
reg    data_symb2_M_imag_V_we1;
reg   [9:0] symb1_M_real_V_address0;
reg    symb1_M_real_V_ce0;
reg    symb1_M_real_V_we0;
wire   [15:0] symb1_M_real_V_q0;
reg   [9:0] symb1_M_imag_V_address0;
reg    symb1_M_imag_V_ce0;
reg    symb1_M_imag_V_we0;
wire   [15:0] symb1_M_imag_V_q0;
reg   [9:0] symb2_M_real_V_address0;
reg    symb2_M_real_V_ce0;
reg    symb2_M_real_V_we0;
wire   [15:0] symb2_M_real_V_q0;
reg   [9:0] symb2_M_imag_V_address0;
reg    symb2_M_imag_V_ce0;
reg    symb2_M_imag_V_we0;
wire   [15:0] symb2_M_imag_V_q0;
wire    grp_adding_pilot_Pipeline_symb_fu_66_ap_start;
wire    grp_adding_pilot_Pipeline_symb_fu_66_ap_done;
wire    grp_adding_pilot_Pipeline_symb_fu_66_ap_idle;
wire    grp_adding_pilot_Pipeline_symb_fu_66_ap_ready;
wire    grp_adding_pilot_Pipeline_symb_fu_66_temp1_re397_read;
wire    grp_adding_pilot_Pipeline_symb_fu_66_temp1_im398_read;
wire   [9:0] grp_adding_pilot_Pipeline_symb_fu_66_symb1_M_real_V_address0;
wire    grp_adding_pilot_Pipeline_symb_fu_66_symb1_M_real_V_ce0;
wire    grp_adding_pilot_Pipeline_symb_fu_66_symb1_M_real_V_we0;
wire   [15:0] grp_adding_pilot_Pipeline_symb_fu_66_symb1_M_real_V_d0;
wire   [9:0] grp_adding_pilot_Pipeline_symb_fu_66_symb1_M_imag_V_address0;
wire    grp_adding_pilot_Pipeline_symb_fu_66_symb1_M_imag_V_ce0;
wire    grp_adding_pilot_Pipeline_symb_fu_66_symb1_M_imag_V_we0;
wire   [15:0] grp_adding_pilot_Pipeline_symb_fu_66_symb1_M_imag_V_d0;
wire   [9:0] grp_adding_pilot_Pipeline_symb_fu_66_symb2_M_real_V_address0;
wire    grp_adding_pilot_Pipeline_symb_fu_66_symb2_M_real_V_ce0;
wire    grp_adding_pilot_Pipeline_symb_fu_66_symb2_M_real_V_we0;
wire   [15:0] grp_adding_pilot_Pipeline_symb_fu_66_symb2_M_real_V_d0;
wire   [9:0] grp_adding_pilot_Pipeline_symb_fu_66_symb2_M_imag_V_address0;
wire    grp_adding_pilot_Pipeline_symb_fu_66_symb2_M_imag_V_ce0;
wire    grp_adding_pilot_Pipeline_symb_fu_66_symb2_M_imag_V_we0;
wire   [15:0] grp_adding_pilot_Pipeline_symb_fu_66_symb2_M_imag_V_d0;
wire    grp_adding_pilot_Pipeline_data_symbol_fu_82_ap_start;
wire    grp_adding_pilot_Pipeline_data_symbol_fu_82_ap_done;
wire    grp_adding_pilot_Pipeline_data_symbol_fu_82_ap_idle;
wire    grp_adding_pilot_Pipeline_data_symbol_fu_82_ap_ready;
wire   [9:0] grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_imag_V_address0;
wire    grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_imag_V_ce0;
wire    grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_imag_V_we0;
wire   [15:0] grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_imag_V_d0;
wire   [9:0] grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_imag_V_address1;
wire    grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_imag_V_ce1;
wire    grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_imag_V_we1;
wire   [15:0] grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_imag_V_d1;
wire   [9:0] grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_real_V_address0;
wire    grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_real_V_ce0;
wire    grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_real_V_we0;
wire   [15:0] grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_real_V_d0;
wire   [9:0] grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_real_V_address1;
wire    grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_real_V_ce1;
wire    grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_real_V_we1;
wire   [15:0] grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_real_V_d1;
wire   [9:0] grp_adding_pilot_Pipeline_data_symbol_fu_82_symb1_M_real_V_address0;
wire    grp_adding_pilot_Pipeline_data_symbol_fu_82_symb1_M_real_V_ce0;
wire   [9:0] grp_adding_pilot_Pipeline_data_symbol_fu_82_symb1_M_imag_V_address0;
wire    grp_adding_pilot_Pipeline_data_symbol_fu_82_symb1_M_imag_V_ce0;
wire    grp_adding_pilot_Pipeline_data_symbo2_fu_90_ap_start;
wire    grp_adding_pilot_Pipeline_data_symbo2_fu_90_ap_done;
wire    grp_adding_pilot_Pipeline_data_symbo2_fu_90_ap_idle;
wire    grp_adding_pilot_Pipeline_data_symbo2_fu_90_ap_ready;
wire   [9:0] grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_imag_V_address0;
wire    grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_imag_V_ce0;
wire    grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_imag_V_we0;
wire   [15:0] grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_imag_V_d0;
wire   [9:0] grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_imag_V_address1;
wire    grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_imag_V_ce1;
wire    grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_imag_V_we1;
wire   [15:0] grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_imag_V_d1;
wire   [9:0] grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_real_V_address0;
wire    grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_real_V_ce0;
wire    grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_real_V_we0;
wire   [15:0] grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_real_V_d0;
wire   [9:0] grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_real_V_address1;
wire    grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_real_V_ce1;
wire    grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_real_V_we1;
wire   [15:0] grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_real_V_d1;
wire   [9:0] grp_adding_pilot_Pipeline_data_symbo2_fu_90_symb2_M_real_V_address0;
wire    grp_adding_pilot_Pipeline_data_symbo2_fu_90_symb2_M_real_V_ce0;
wire   [9:0] grp_adding_pilot_Pipeline_data_symbo2_fu_90_symb2_M_imag_V_address0;
wire    grp_adding_pilot_Pipeline_data_symbo2_fu_90_symb2_M_imag_V_ce0;
wire    grp_adding_pilot_Pipeline_output_arrangement_fu_98_ap_start;
wire    grp_adding_pilot_Pipeline_output_arrangement_fu_98_ap_done;
wire    grp_adding_pilot_Pipeline_output_arrangement_fu_98_ap_idle;
wire    grp_adding_pilot_Pipeline_output_arrangement_fu_98_ap_ready;
wire   [15:0] grp_adding_pilot_Pipeline_output_arrangement_fu_98_temp2_re399_din;
wire    grp_adding_pilot_Pipeline_output_arrangement_fu_98_temp2_re399_write;
wire   [15:0] grp_adding_pilot_Pipeline_output_arrangement_fu_98_temp2_im400_din;
wire    grp_adding_pilot_Pipeline_output_arrangement_fu_98_temp2_im400_write;
wire   [9:0] grp_adding_pilot_Pipeline_output_arrangement_fu_98_data_symb1_M_real_V_address0;
wire    grp_adding_pilot_Pipeline_output_arrangement_fu_98_data_symb1_M_real_V_ce0;
wire   [9:0] grp_adding_pilot_Pipeline_output_arrangement_fu_98_data_symb1_M_imag_V_address0;
wire    grp_adding_pilot_Pipeline_output_arrangement_fu_98_data_symb1_M_imag_V_ce0;
wire   [9:0] grp_adding_pilot_Pipeline_output_arrangement_fu_98_data_symb2_M_real_V_address0;
wire    grp_adding_pilot_Pipeline_output_arrangement_fu_98_data_symb2_M_real_V_ce0;
wire   [9:0] grp_adding_pilot_Pipeline_output_arrangement_fu_98_data_symb2_M_imag_V_address0;
wire    grp_adding_pilot_Pipeline_output_arrangement_fu_98_data_symb2_M_imag_V_ce0;
reg    grp_adding_pilot_Pipeline_symb_fu_66_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_adding_pilot_Pipeline_data_symbol_fu_82_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_adding_pilot_Pipeline_data_symbo2_fu_90_ap_start_reg;
reg    grp_adding_pilot_Pipeline_output_arrangement_fu_98_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_block_state4_on_subcall_done;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_adding_pilot_Pipeline_symb_fu_66_ap_start_reg = 1'b0;
#0 grp_adding_pilot_Pipeline_data_symbol_fu_82_ap_start_reg = 1'b0;
#0 grp_adding_pilot_Pipeline_data_symbo2_fu_90_ap_start_reg = 1'b0;
#0 grp_adding_pilot_Pipeline_output_arrangement_fu_98_ap_start_reg = 1'b0;
end

top_tx_adding_pilot_data_symb1_M_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
data_symb1_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(data_symb1_M_real_V_address0),
    .ce0(data_symb1_M_real_V_ce0),
    .we0(data_symb1_M_real_V_we0),
    .d0(grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_real_V_d0),
    .q0(data_symb1_M_real_V_q0),
    .address1(grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_real_V_address1),
    .ce1(data_symb1_M_real_V_ce1),
    .we1(data_symb1_M_real_V_we1),
    .d1(grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_real_V_d1)
);

top_tx_adding_pilot_data_symb1_M_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
data_symb1_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(data_symb1_M_imag_V_address0),
    .ce0(data_symb1_M_imag_V_ce0),
    .we0(data_symb1_M_imag_V_we0),
    .d0(grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_imag_V_d0),
    .q0(data_symb1_M_imag_V_q0),
    .address1(grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_imag_V_address1),
    .ce1(data_symb1_M_imag_V_ce1),
    .we1(data_symb1_M_imag_V_we1),
    .d1(grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_imag_V_d1)
);

top_tx_adding_pilot_data_symb1_M_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
data_symb2_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(data_symb2_M_real_V_address0),
    .ce0(data_symb2_M_real_V_ce0),
    .we0(data_symb2_M_real_V_we0),
    .d0(grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_real_V_d0),
    .q0(data_symb2_M_real_V_q0),
    .address1(grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_real_V_address1),
    .ce1(data_symb2_M_real_V_ce1),
    .we1(data_symb2_M_real_V_we1),
    .d1(grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_real_V_d1)
);

top_tx_adding_pilot_data_symb1_M_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
data_symb2_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(data_symb2_M_imag_V_address0),
    .ce0(data_symb2_M_imag_V_ce0),
    .we0(data_symb2_M_imag_V_we0),
    .d0(grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_imag_V_d0),
    .q0(data_symb2_M_imag_V_q0),
    .address1(grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_imag_V_address1),
    .ce1(data_symb2_M_imag_V_ce1),
    .we1(data_symb2_M_imag_V_we1),
    .d1(grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_imag_V_d1)
);

top_tx_adding_pilot_symb1_M_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 600 ),
    .AddressWidth( 10 ))
symb1_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(symb1_M_real_V_address0),
    .ce0(symb1_M_real_V_ce0),
    .we0(symb1_M_real_V_we0),
    .d0(grp_adding_pilot_Pipeline_symb_fu_66_symb1_M_real_V_d0),
    .q0(symb1_M_real_V_q0)
);

top_tx_adding_pilot_symb1_M_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 600 ),
    .AddressWidth( 10 ))
symb1_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(symb1_M_imag_V_address0),
    .ce0(symb1_M_imag_V_ce0),
    .we0(symb1_M_imag_V_we0),
    .d0(grp_adding_pilot_Pipeline_symb_fu_66_symb1_M_imag_V_d0),
    .q0(symb1_M_imag_V_q0)
);

top_tx_adding_pilot_symb1_M_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 600 ),
    .AddressWidth( 10 ))
symb2_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(symb2_M_real_V_address0),
    .ce0(symb2_M_real_V_ce0),
    .we0(symb2_M_real_V_we0),
    .d0(grp_adding_pilot_Pipeline_symb_fu_66_symb2_M_real_V_d0),
    .q0(symb2_M_real_V_q0)
);

top_tx_adding_pilot_symb1_M_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 600 ),
    .AddressWidth( 10 ))
symb2_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(symb2_M_imag_V_address0),
    .ce0(symb2_M_imag_V_ce0),
    .we0(symb2_M_imag_V_we0),
    .d0(grp_adding_pilot_Pipeline_symb_fu_66_symb2_M_imag_V_d0),
    .q0(symb2_M_imag_V_q0)
);

top_tx_adding_pilot_Pipeline_symb grp_adding_pilot_Pipeline_symb_fu_66(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_adding_pilot_Pipeline_symb_fu_66_ap_start),
    .ap_done(grp_adding_pilot_Pipeline_symb_fu_66_ap_done),
    .ap_idle(grp_adding_pilot_Pipeline_symb_fu_66_ap_idle),
    .ap_ready(grp_adding_pilot_Pipeline_symb_fu_66_ap_ready),
    .temp1_re397_dout(temp1_re397_dout),
    .temp1_re397_empty_n(temp1_re397_empty_n),
    .temp1_re397_read(grp_adding_pilot_Pipeline_symb_fu_66_temp1_re397_read),
    .temp1_im398_dout(temp1_im398_dout),
    .temp1_im398_empty_n(temp1_im398_empty_n),
    .temp1_im398_read(grp_adding_pilot_Pipeline_symb_fu_66_temp1_im398_read),
    .symb1_M_real_V_address0(grp_adding_pilot_Pipeline_symb_fu_66_symb1_M_real_V_address0),
    .symb1_M_real_V_ce0(grp_adding_pilot_Pipeline_symb_fu_66_symb1_M_real_V_ce0),
    .symb1_M_real_V_we0(grp_adding_pilot_Pipeline_symb_fu_66_symb1_M_real_V_we0),
    .symb1_M_real_V_d0(grp_adding_pilot_Pipeline_symb_fu_66_symb1_M_real_V_d0),
    .symb1_M_imag_V_address0(grp_adding_pilot_Pipeline_symb_fu_66_symb1_M_imag_V_address0),
    .symb1_M_imag_V_ce0(grp_adding_pilot_Pipeline_symb_fu_66_symb1_M_imag_V_ce0),
    .symb1_M_imag_V_we0(grp_adding_pilot_Pipeline_symb_fu_66_symb1_M_imag_V_we0),
    .symb1_M_imag_V_d0(grp_adding_pilot_Pipeline_symb_fu_66_symb1_M_imag_V_d0),
    .symb2_M_real_V_address0(grp_adding_pilot_Pipeline_symb_fu_66_symb2_M_real_V_address0),
    .symb2_M_real_V_ce0(grp_adding_pilot_Pipeline_symb_fu_66_symb2_M_real_V_ce0),
    .symb2_M_real_V_we0(grp_adding_pilot_Pipeline_symb_fu_66_symb2_M_real_V_we0),
    .symb2_M_real_V_d0(grp_adding_pilot_Pipeline_symb_fu_66_symb2_M_real_V_d0),
    .symb2_M_imag_V_address0(grp_adding_pilot_Pipeline_symb_fu_66_symb2_M_imag_V_address0),
    .symb2_M_imag_V_ce0(grp_adding_pilot_Pipeline_symb_fu_66_symb2_M_imag_V_ce0),
    .symb2_M_imag_V_we0(grp_adding_pilot_Pipeline_symb_fu_66_symb2_M_imag_V_we0),
    .symb2_M_imag_V_d0(grp_adding_pilot_Pipeline_symb_fu_66_symb2_M_imag_V_d0)
);

top_tx_adding_pilot_Pipeline_data_symbol grp_adding_pilot_Pipeline_data_symbol_fu_82(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_adding_pilot_Pipeline_data_symbol_fu_82_ap_start),
    .ap_done(grp_adding_pilot_Pipeline_data_symbol_fu_82_ap_done),
    .ap_idle(grp_adding_pilot_Pipeline_data_symbol_fu_82_ap_idle),
    .ap_ready(grp_adding_pilot_Pipeline_data_symbol_fu_82_ap_ready),
    .data_symb1_M_imag_V_address0(grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_imag_V_address0),
    .data_symb1_M_imag_V_ce0(grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_imag_V_ce0),
    .data_symb1_M_imag_V_we0(grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_imag_V_we0),
    .data_symb1_M_imag_V_d0(grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_imag_V_d0),
    .data_symb1_M_imag_V_address1(grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_imag_V_address1),
    .data_symb1_M_imag_V_ce1(grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_imag_V_ce1),
    .data_symb1_M_imag_V_we1(grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_imag_V_we1),
    .data_symb1_M_imag_V_d1(grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_imag_V_d1),
    .data_symb1_M_real_V_address0(grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_real_V_address0),
    .data_symb1_M_real_V_ce0(grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_real_V_ce0),
    .data_symb1_M_real_V_we0(grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_real_V_we0),
    .data_symb1_M_real_V_d0(grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_real_V_d0),
    .data_symb1_M_real_V_address1(grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_real_V_address1),
    .data_symb1_M_real_V_ce1(grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_real_V_ce1),
    .data_symb1_M_real_V_we1(grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_real_V_we1),
    .data_symb1_M_real_V_d1(grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_real_V_d1),
    .symb1_M_real_V_address0(grp_adding_pilot_Pipeline_data_symbol_fu_82_symb1_M_real_V_address0),
    .symb1_M_real_V_ce0(grp_adding_pilot_Pipeline_data_symbol_fu_82_symb1_M_real_V_ce0),
    .symb1_M_real_V_q0(symb1_M_real_V_q0),
    .symb1_M_imag_V_address0(grp_adding_pilot_Pipeline_data_symbol_fu_82_symb1_M_imag_V_address0),
    .symb1_M_imag_V_ce0(grp_adding_pilot_Pipeline_data_symbol_fu_82_symb1_M_imag_V_ce0),
    .symb1_M_imag_V_q0(symb1_M_imag_V_q0)
);

top_tx_adding_pilot_Pipeline_data_symbo2 grp_adding_pilot_Pipeline_data_symbo2_fu_90(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_adding_pilot_Pipeline_data_symbo2_fu_90_ap_start),
    .ap_done(grp_adding_pilot_Pipeline_data_symbo2_fu_90_ap_done),
    .ap_idle(grp_adding_pilot_Pipeline_data_symbo2_fu_90_ap_idle),
    .ap_ready(grp_adding_pilot_Pipeline_data_symbo2_fu_90_ap_ready),
    .data_symb2_M_imag_V_address0(grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_imag_V_address0),
    .data_symb2_M_imag_V_ce0(grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_imag_V_ce0),
    .data_symb2_M_imag_V_we0(grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_imag_V_we0),
    .data_symb2_M_imag_V_d0(grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_imag_V_d0),
    .data_symb2_M_imag_V_address1(grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_imag_V_address1),
    .data_symb2_M_imag_V_ce1(grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_imag_V_ce1),
    .data_symb2_M_imag_V_we1(grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_imag_V_we1),
    .data_symb2_M_imag_V_d1(grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_imag_V_d1),
    .data_symb2_M_real_V_address0(grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_real_V_address0),
    .data_symb2_M_real_V_ce0(grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_real_V_ce0),
    .data_symb2_M_real_V_we0(grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_real_V_we0),
    .data_symb2_M_real_V_d0(grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_real_V_d0),
    .data_symb2_M_real_V_address1(grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_real_V_address1),
    .data_symb2_M_real_V_ce1(grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_real_V_ce1),
    .data_symb2_M_real_V_we1(grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_real_V_we1),
    .data_symb2_M_real_V_d1(grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_real_V_d1),
    .symb2_M_real_V_address0(grp_adding_pilot_Pipeline_data_symbo2_fu_90_symb2_M_real_V_address0),
    .symb2_M_real_V_ce0(grp_adding_pilot_Pipeline_data_symbo2_fu_90_symb2_M_real_V_ce0),
    .symb2_M_real_V_q0(symb2_M_real_V_q0),
    .symb2_M_imag_V_address0(grp_adding_pilot_Pipeline_data_symbo2_fu_90_symb2_M_imag_V_address0),
    .symb2_M_imag_V_ce0(grp_adding_pilot_Pipeline_data_symbo2_fu_90_symb2_M_imag_V_ce0),
    .symb2_M_imag_V_q0(symb2_M_imag_V_q0)
);

top_tx_adding_pilot_Pipeline_output_arrangement grp_adding_pilot_Pipeline_output_arrangement_fu_98(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_adding_pilot_Pipeline_output_arrangement_fu_98_ap_start),
    .ap_done(grp_adding_pilot_Pipeline_output_arrangement_fu_98_ap_done),
    .ap_idle(grp_adding_pilot_Pipeline_output_arrangement_fu_98_ap_idle),
    .ap_ready(grp_adding_pilot_Pipeline_output_arrangement_fu_98_ap_ready),
    .temp2_re399_din(grp_adding_pilot_Pipeline_output_arrangement_fu_98_temp2_re399_din),
    .temp2_re399_full_n(temp2_re399_full_n),
    .temp2_re399_write(grp_adding_pilot_Pipeline_output_arrangement_fu_98_temp2_re399_write),
    .temp2_im400_din(grp_adding_pilot_Pipeline_output_arrangement_fu_98_temp2_im400_din),
    .temp2_im400_full_n(temp2_im400_full_n),
    .temp2_im400_write(grp_adding_pilot_Pipeline_output_arrangement_fu_98_temp2_im400_write),
    .data_symb1_M_real_V_address0(grp_adding_pilot_Pipeline_output_arrangement_fu_98_data_symb1_M_real_V_address0),
    .data_symb1_M_real_V_ce0(grp_adding_pilot_Pipeline_output_arrangement_fu_98_data_symb1_M_real_V_ce0),
    .data_symb1_M_real_V_q0(data_symb1_M_real_V_q0),
    .data_symb1_M_imag_V_address0(grp_adding_pilot_Pipeline_output_arrangement_fu_98_data_symb1_M_imag_V_address0),
    .data_symb1_M_imag_V_ce0(grp_adding_pilot_Pipeline_output_arrangement_fu_98_data_symb1_M_imag_V_ce0),
    .data_symb1_M_imag_V_q0(data_symb1_M_imag_V_q0),
    .data_symb2_M_real_V_address0(grp_adding_pilot_Pipeline_output_arrangement_fu_98_data_symb2_M_real_V_address0),
    .data_symb2_M_real_V_ce0(grp_adding_pilot_Pipeline_output_arrangement_fu_98_data_symb2_M_real_V_ce0),
    .data_symb2_M_real_V_q0(data_symb2_M_real_V_q0),
    .data_symb2_M_imag_V_address0(grp_adding_pilot_Pipeline_output_arrangement_fu_98_data_symb2_M_imag_V_address0),
    .data_symb2_M_imag_V_ce0(grp_adding_pilot_Pipeline_output_arrangement_fu_98_data_symb2_M_imag_V_ce0),
    .data_symb2_M_imag_V_q0(data_symb2_M_imag_V_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_adding_pilot_Pipeline_data_symbo2_fu_90_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_adding_pilot_Pipeline_data_symbo2_fu_90_ap_start_reg <= 1'b1;
        end else if ((grp_adding_pilot_Pipeline_data_symbo2_fu_90_ap_ready == 1'b1)) begin
            grp_adding_pilot_Pipeline_data_symbo2_fu_90_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_adding_pilot_Pipeline_data_symbol_fu_82_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_adding_pilot_Pipeline_data_symbol_fu_82_ap_start_reg <= 1'b1;
        end else if ((grp_adding_pilot_Pipeline_data_symbol_fu_82_ap_ready == 1'b1)) begin
            grp_adding_pilot_Pipeline_data_symbol_fu_82_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_adding_pilot_Pipeline_output_arrangement_fu_98_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_adding_pilot_Pipeline_output_arrangement_fu_98_ap_start_reg <= 1'b1;
        end else if ((grp_adding_pilot_Pipeline_output_arrangement_fu_98_ap_ready == 1'b1)) begin
            grp_adding_pilot_Pipeline_output_arrangement_fu_98_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_adding_pilot_Pipeline_symb_fu_66_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_adding_pilot_Pipeline_symb_fu_66_ap_start_reg <= 1'b1;
        end else if ((grp_adding_pilot_Pipeline_symb_fu_66_ap_ready == 1'b1)) begin
            grp_adding_pilot_Pipeline_symb_fu_66_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_adding_pilot_Pipeline_symb_fu_66_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state4_on_subcall_done)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_adding_pilot_Pipeline_output_arrangement_fu_98_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((grp_adding_pilot_Pipeline_output_arrangement_fu_98_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_adding_pilot_Pipeline_output_arrangement_fu_98_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        data_symb1_M_imag_V_address0 = grp_adding_pilot_Pipeline_output_arrangement_fu_98_data_symb1_M_imag_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        data_symb1_M_imag_V_address0 = grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_imag_V_address0;
    end else begin
        data_symb1_M_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        data_symb1_M_imag_V_ce0 = grp_adding_pilot_Pipeline_output_arrangement_fu_98_data_symb1_M_imag_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        data_symb1_M_imag_V_ce0 = grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_imag_V_ce0;
    end else begin
        data_symb1_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        data_symb1_M_imag_V_ce1 = grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_imag_V_ce1;
    end else begin
        data_symb1_M_imag_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        data_symb1_M_imag_V_we0 = grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_imag_V_we0;
    end else begin
        data_symb1_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        data_symb1_M_imag_V_we1 = grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_imag_V_we1;
    end else begin
        data_symb1_M_imag_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        data_symb1_M_real_V_address0 = grp_adding_pilot_Pipeline_output_arrangement_fu_98_data_symb1_M_real_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        data_symb1_M_real_V_address0 = grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_real_V_address0;
    end else begin
        data_symb1_M_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        data_symb1_M_real_V_ce0 = grp_adding_pilot_Pipeline_output_arrangement_fu_98_data_symb1_M_real_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        data_symb1_M_real_V_ce0 = grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_real_V_ce0;
    end else begin
        data_symb1_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        data_symb1_M_real_V_ce1 = grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_real_V_ce1;
    end else begin
        data_symb1_M_real_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        data_symb1_M_real_V_we0 = grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_real_V_we0;
    end else begin
        data_symb1_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        data_symb1_M_real_V_we1 = grp_adding_pilot_Pipeline_data_symbol_fu_82_data_symb1_M_real_V_we1;
    end else begin
        data_symb1_M_real_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        data_symb2_M_imag_V_address0 = grp_adding_pilot_Pipeline_output_arrangement_fu_98_data_symb2_M_imag_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        data_symb2_M_imag_V_address0 = grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_imag_V_address0;
    end else begin
        data_symb2_M_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        data_symb2_M_imag_V_ce0 = grp_adding_pilot_Pipeline_output_arrangement_fu_98_data_symb2_M_imag_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        data_symb2_M_imag_V_ce0 = grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_imag_V_ce0;
    end else begin
        data_symb2_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        data_symb2_M_imag_V_ce1 = grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_imag_V_ce1;
    end else begin
        data_symb2_M_imag_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        data_symb2_M_imag_V_we0 = grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_imag_V_we0;
    end else begin
        data_symb2_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        data_symb2_M_imag_V_we1 = grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_imag_V_we1;
    end else begin
        data_symb2_M_imag_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        data_symb2_M_real_V_address0 = grp_adding_pilot_Pipeline_output_arrangement_fu_98_data_symb2_M_real_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        data_symb2_M_real_V_address0 = grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_real_V_address0;
    end else begin
        data_symb2_M_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        data_symb2_M_real_V_ce0 = grp_adding_pilot_Pipeline_output_arrangement_fu_98_data_symb2_M_real_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        data_symb2_M_real_V_ce0 = grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_real_V_ce0;
    end else begin
        data_symb2_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        data_symb2_M_real_V_ce1 = grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_real_V_ce1;
    end else begin
        data_symb2_M_real_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        data_symb2_M_real_V_we0 = grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_real_V_we0;
    end else begin
        data_symb2_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        data_symb2_M_real_V_we1 = grp_adding_pilot_Pipeline_data_symbo2_fu_90_data_symb2_M_real_V_we1;
    end else begin
        data_symb2_M_real_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        symb1_M_imag_V_address0 = grp_adding_pilot_Pipeline_data_symbol_fu_82_symb1_M_imag_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        symb1_M_imag_V_address0 = grp_adding_pilot_Pipeline_symb_fu_66_symb1_M_imag_V_address0;
    end else begin
        symb1_M_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        symb1_M_imag_V_ce0 = grp_adding_pilot_Pipeline_data_symbol_fu_82_symb1_M_imag_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        symb1_M_imag_V_ce0 = grp_adding_pilot_Pipeline_symb_fu_66_symb1_M_imag_V_ce0;
    end else begin
        symb1_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        symb1_M_imag_V_we0 = grp_adding_pilot_Pipeline_symb_fu_66_symb1_M_imag_V_we0;
    end else begin
        symb1_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        symb1_M_real_V_address0 = grp_adding_pilot_Pipeline_data_symbol_fu_82_symb1_M_real_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        symb1_M_real_V_address0 = grp_adding_pilot_Pipeline_symb_fu_66_symb1_M_real_V_address0;
    end else begin
        symb1_M_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        symb1_M_real_V_ce0 = grp_adding_pilot_Pipeline_data_symbol_fu_82_symb1_M_real_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        symb1_M_real_V_ce0 = grp_adding_pilot_Pipeline_symb_fu_66_symb1_M_real_V_ce0;
    end else begin
        symb1_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        symb1_M_real_V_we0 = grp_adding_pilot_Pipeline_symb_fu_66_symb1_M_real_V_we0;
    end else begin
        symb1_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        symb2_M_imag_V_address0 = grp_adding_pilot_Pipeline_data_symbo2_fu_90_symb2_M_imag_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        symb2_M_imag_V_address0 = grp_adding_pilot_Pipeline_symb_fu_66_symb2_M_imag_V_address0;
    end else begin
        symb2_M_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        symb2_M_imag_V_ce0 = grp_adding_pilot_Pipeline_data_symbo2_fu_90_symb2_M_imag_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        symb2_M_imag_V_ce0 = grp_adding_pilot_Pipeline_symb_fu_66_symb2_M_imag_V_ce0;
    end else begin
        symb2_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        symb2_M_imag_V_we0 = grp_adding_pilot_Pipeline_symb_fu_66_symb2_M_imag_V_we0;
    end else begin
        symb2_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        symb2_M_real_V_address0 = grp_adding_pilot_Pipeline_data_symbo2_fu_90_symb2_M_real_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        symb2_M_real_V_address0 = grp_adding_pilot_Pipeline_symb_fu_66_symb2_M_real_V_address0;
    end else begin
        symb2_M_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        symb2_M_real_V_ce0 = grp_adding_pilot_Pipeline_data_symbo2_fu_90_symb2_M_real_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        symb2_M_real_V_ce0 = grp_adding_pilot_Pipeline_symb_fu_66_symb2_M_real_V_ce0;
    end else begin
        symb2_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        symb2_M_real_V_we0 = grp_adding_pilot_Pipeline_symb_fu_66_symb2_M_real_V_we0;
    end else begin
        symb2_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        temp1_im398_read = grp_adding_pilot_Pipeline_symb_fu_66_temp1_im398_read;
    end else begin
        temp1_im398_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        temp1_re397_read = grp_adding_pilot_Pipeline_symb_fu_66_temp1_re397_read;
    end else begin
        temp1_re397_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        temp2_im400_write = grp_adding_pilot_Pipeline_output_arrangement_fu_98_temp2_im400_write;
    end else begin
        temp2_im400_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        temp2_re399_write = grp_adding_pilot_Pipeline_output_arrangement_fu_98_temp2_re399_write;
    end else begin
        temp2_re399_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_adding_pilot_Pipeline_symb_fu_66_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_adding_pilot_Pipeline_output_arrangement_fu_98_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state4_on_subcall_done = ((grp_adding_pilot_Pipeline_data_symbo2_fu_90_ap_done == 1'b0) | (grp_adding_pilot_Pipeline_data_symbol_fu_82_ap_done == 1'b0));
end

assign grp_adding_pilot_Pipeline_data_symbo2_fu_90_ap_start = grp_adding_pilot_Pipeline_data_symbo2_fu_90_ap_start_reg;

assign grp_adding_pilot_Pipeline_data_symbol_fu_82_ap_start = grp_adding_pilot_Pipeline_data_symbol_fu_82_ap_start_reg;

assign grp_adding_pilot_Pipeline_output_arrangement_fu_98_ap_start = grp_adding_pilot_Pipeline_output_arrangement_fu_98_ap_start_reg;

assign grp_adding_pilot_Pipeline_symb_fu_66_ap_start = grp_adding_pilot_Pipeline_symb_fu_66_ap_start_reg;

assign temp2_im400_din = grp_adding_pilot_Pipeline_output_arrangement_fu_98_temp2_im400_din;

assign temp2_re399_din = grp_adding_pilot_Pipeline_output_arrangement_fu_98_temp2_re399_din;

endmodule //top_tx_adding_pilot
